//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package au.com.jtribe.lejos;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import au.com.jtribe.lejos.R.id;
import au.com.jtribe.lejos.R.layout;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class DroidNXTRemoteActivity_
    extends DroidNXTRemoteActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.main);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        startButton = ((Button) findViewById(id.startButton));
        connectButton = ((Button) findViewById(id.connectButton));
        bindButton = ((Button) findViewById(id.bindButton));
        {
            View view = findViewById(id.leftButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        leftButtonPressed();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.startButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        startButtonPressed();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.forwardButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        forwardButtonPressed();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.rightButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        rightButtonPressed();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.connectButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        connectButtonPressed();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.bindButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        bindButtonPressed();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.backwardButton);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    public void onClick(View view) {
                        backwardButtonPressed();
                    }

                }
                );
            }
        }
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static DroidNXTRemoteActivity_.IntentBuilder_ intent(Context context) {
        return new DroidNXTRemoteActivity_.IntentBuilder_(context);
    }

    @Override
    public void renderConnectButton() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    DroidNXTRemoteActivity_.super.renderConnectButton();
                } catch (RuntimeException e) {
                    Log.e("DroidNXTRemoteActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void renderBindButton() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    DroidNXTRemoteActivity_.super.renderBindButton();
                } catch (RuntimeException e) {
                    Log.e("DroidNXTRemoteActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void requestNXTConnection() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    DroidNXTRemoteActivity_.super.requestNXTConnection();
                } catch (RuntimeException e) {
                    Log.e("DroidNXTRemoteActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, DroidNXTRemoteActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public DroidNXTRemoteActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

    }

}
